== Exercise

For practice, we will create a very simple client/server Hello world program.

We will make two applications:
 * One that provide an HTTP Get endpoint that send "Hello" plain text response.
 * Another that will call the API above, and print it in the console.

=== Step 1 : create the project

First and foremost, we'll use https://start.spring.io[Spring online starter] to create a simple application with *Reactive web* support.

. Go to the linked page
. choose your preferred language and build system (radio buttons on the left)
. Specify a package, title, etc.
. On the right side, use *add dependencies* button to search and add *Reactive web*.
. Download the project template with *Generate* button at the bottom of the page

=== Step 2: Web service

. Then, we will add a REST controller with a "hello" method.
.. Create a class *HelloService*. Annotate it with `@RestController`.
.. Add a method returning a `Mono<String>` and annotate it with `@GetMapping`
.. Fill its body to "just" return a constant message (hint: look at the Mono API).

You can test it by opening browser on link:http:localhost:8080/hello[].

=== Step 3: Web client and profiles

Now, we want a Spring Boot app as client. To do so, we will keep using our app, but:

. We will add a new client component. It will be a command line program, doing a one-shot execution.
.. Tip 1: look at https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/CommandLineRunner.html[CommandLineRunner] or https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/ApplicationRunner.html[ApplicationRunner] interfaces.
.. Tip 2: When running our app as a one-shot command, we do not want it https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto.application.non-web-application[to start a web service environment].
. To run server and client separately, we have to associate different profiles to our server and client components.

=== Step 4: exchange names

Now that we have a working couple of services answering each other, we will add custom behavior to familiarize with external variables.

. First, we will define a common property to both client and server: `app.name`.
.. Client will use its name as referer.
.. Server will display it in its response.
.. As a bonus, try to retrieve client request referer and display it in response message.
. Then, we will "bind" the standard `spring.application.name` to our `app-name` concatenated with the active profile. We will use the capability to give as variable value  property names to resolve later

=== Step 5: add a delay

Externalized configuration can do type conversion, so you can rely directly on property model, rather than using it as an intermediate representation only.
Let'see an example: imagine we want to configure a limite rate for server responses. We can use externalize configuration to provide a delay before answering a request.

. Add a `delay` properties of type `java.time.Duration` in application properties.
. Inject it / use it in both client and server to force delaying request/response.
. Bonus:
.. make delay optional, and provide a null value to the client, so only the server will add a delay on its response time.
.. Define a different delay for both client and server
.. Print delayed amount of time (tip: look at https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Mono.html#timed--[Mono.timed()])
